// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/0x5d/shiru/internal/domain (interfaces: UserRepository)
//
// Generated by this command:
//
//	mockgen -destination mock/mock_user_repository.go -package mock . UserRepository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/0x5d/shiru/internal/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// EnsureUserSettings mocks base method.
func (m *MockUserRepository) EnsureUserSettings(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureUserSettings", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureUserSettings indicates an expected call of EnsureUserSettings.
func (mr *MockUserRepositoryMockRecorder) EnsureUserSettings(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureUserSettings", reflect.TypeOf((*MockUserRepository)(nil).EnsureUserSettings), ctx, userID)
}

// GetByID mocks base method.
func (m *MockUserRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserRepository)(nil).GetByID), ctx, id)
}

// UpsertGoogleUser mocks base method.
func (m *MockUserRepository) UpsertGoogleUser(ctx context.Context, googleSub, email, name, avatarURL string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertGoogleUser", ctx, googleSub, email, name, avatarURL)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertGoogleUser indicates an expected call of UpsertGoogleUser.
func (mr *MockUserRepositoryMockRecorder) UpsertGoogleUser(ctx, googleSub, email, name, avatarURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertGoogleUser", reflect.TypeOf((*MockUserRepository)(nil).UpsertGoogleUser), ctx, googleSub, email, name, avatarURL)
}
