// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/0x5d/shiru/internal/domain (interfaces: SettingsRepository)
//
// Generated by this command:
//
//	mockgen -destination mock/mock_settings_repository.go -package mock . SettingsRepository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/0x5d/shiru/internal/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockSettingsRepository is a mock of SettingsRepository interface.
type MockSettingsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSettingsRepositoryMockRecorder
	isgomock struct{}
}

// MockSettingsRepositoryMockRecorder is the mock recorder for MockSettingsRepository.
type MockSettingsRepositoryMockRecorder struct {
	mock *MockSettingsRepository
}

// NewMockSettingsRepository creates a new mock instance.
func NewMockSettingsRepository(ctrl *gomock.Controller) *MockSettingsRepository {
	mock := &MockSettingsRepository{ctrl: ctrl}
	mock.recorder = &MockSettingsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSettingsRepository) EXPECT() *MockSettingsRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockSettingsRepository) Get(ctx context.Context, userID uuid.UUID) (*domain.UserSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, userID)
	ret0, _ := ret[0].(*domain.UserSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSettingsRepositoryMockRecorder) Get(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSettingsRepository)(nil).Get), ctx, userID)
}

// ResetWaniKaniSyncedAt mocks base method.
func (m *MockSettingsRepository) ResetWaniKaniSyncedAt(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetWaniKaniSyncedAt", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetWaniKaniSyncedAt indicates an expected call of ResetWaniKaniSyncedAt.
func (mr *MockSettingsRepositoryMockRecorder) ResetWaniKaniSyncedAt(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetWaniKaniSyncedAt", reflect.TypeOf((*MockSettingsRepository)(nil).ResetWaniKaniSyncedAt), ctx, userID)
}

// Update mocks base method.
func (m *MockSettingsRepository) Update(ctx context.Context, userID uuid.UUID, jlptLevel string, storyWordTarget int, wanikaniAPIKey *string) (*domain.UserSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, userID, jlptLevel, storyWordTarget, wanikaniAPIKey)
	ret0, _ := ret[0].(*domain.UserSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockSettingsRepositoryMockRecorder) Update(ctx, userID, jlptLevel, storyWordTarget, wanikaniAPIKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSettingsRepository)(nil).Update), ctx, userID, jlptLevel, storyWordTarget, wanikaniAPIKey)
}

// UpdateWaniKaniSyncedAt mocks base method.
func (m *MockSettingsRepository) UpdateWaniKaniSyncedAt(ctx context.Context, userID uuid.UUID, syncedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWaniKaniSyncedAt", ctx, userID, syncedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateWaniKaniSyncedAt indicates an expected call of UpdateWaniKaniSyncedAt.
func (mr *MockSettingsRepositoryMockRecorder) UpdateWaniKaniSyncedAt(ctx, userID, syncedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWaniKaniSyncedAt", reflect.TypeOf((*MockSettingsRepository)(nil).UpdateWaniKaniSyncedAt), ctx, userID, syncedAt)
}
