// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/0x5d/shiru/internal/domain (interfaces: VocabRepository)
//
// Generated by this command:
//
//	mockgen -destination mock/mock_vocab_repository.go -package mock . VocabRepository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/0x5d/shiru/internal/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockVocabRepository is a mock of VocabRepository interface.
type MockVocabRepository struct {
	ctrl     *gomock.Controller
	recorder *MockVocabRepositoryMockRecorder
	isgomock struct{}
}

// MockVocabRepositoryMockRecorder is the mock recorder for MockVocabRepository.
type MockVocabRepositoryMockRecorder struct {
	mock *MockVocabRepository
}

// NewMockVocabRepository creates a new mock instance.
func NewMockVocabRepository(ctrl *gomock.Controller) *MockVocabRepository {
	mock := &MockVocabRepository{ctrl: ctrl}
	mock.recorder = &MockVocabRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVocabRepository) EXPECT() *MockVocabRepositoryMockRecorder {
	return m.recorder
}

// BatchUpsert mocks base method.
func (m *MockVocabRepository) BatchUpsert(ctx context.Context, userID uuid.UUID, surfaces []string, source string) ([]domain.VocabEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpsert", ctx, userID, surfaces, source)
	ret0, _ := ret[0].([]domain.VocabEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchUpsert indicates an expected call of BatchUpsert.
func (mr *MockVocabRepositoryMockRecorder) BatchUpsert(ctx, userID, surfaces, source any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpsert", reflect.TypeOf((*MockVocabRepository)(nil).BatchUpsert), ctx, userID, surfaces, source)
}

// List mocks base method.
func (m *MockVocabRepository) List(ctx context.Context, userID uuid.UUID, query string, limit, offset int) ([]domain.VocabEntry, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userID, query, limit, offset)
	ret0, _ := ret[0].([]domain.VocabEntry)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockVocabRepositoryMockRecorder) List(ctx, userID, query, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockVocabRepository)(nil).List), ctx, userID, query, limit, offset)
}
