// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/0x5d/shiru/internal/story (interfaces: Indexer)
//
// Generated by this command:
//
//	mockgen -destination mock/indexer.go -package mock . Indexer
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	story "github.com/0x5d/shiru/internal/story"
	gomock "go.uber.org/mock/gomock"
)

// MockIndexer is a mock of Indexer interface.
type MockIndexer struct {
	ctrl     *gomock.Controller
	recorder *MockIndexerMockRecorder
	isgomock struct{}
}

// MockIndexerMockRecorder is the mock recorder for MockIndexer.
type MockIndexerMockRecorder struct {
	mock *MockIndexer
}

// NewMockIndexer creates a new mock instance.
func NewMockIndexer(ctrl *gomock.Controller) *MockIndexer {
	mock := &MockIndexer{ctrl: ctrl}
	mock.recorder = &MockIndexerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIndexer) EXPECT() *MockIndexerMockRecorder {
	return m.recorder
}

// Index mocks base method.
func (m *MockIndexer) Index(ctx context.Context, arg1 *story.Story) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Index", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Index indicates an expected call of Index.
func (mr *MockIndexerMockRecorder) Index(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Index", reflect.TypeOf((*MockIndexer)(nil).Index), ctx, arg1)
}
