// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/0x5d/shiru/internal/story (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination mock/repository.go -package mock . Repository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	story "github.com/0x5d/shiru/internal/story"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AddVocabEntries mocks base method.
func (m *MockRepository) AddVocabEntries(ctx context.Context, storyID uuid.UUID, vocabEntryIDs []uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddVocabEntries", ctx, storyID, vocabEntryIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddVocabEntries indicates an expected call of AddVocabEntries.
func (mr *MockRepositoryMockRecorder) AddVocabEntries(ctx, storyID, vocabEntryIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddVocabEntries", reflect.TypeOf((*MockRepository)(nil).AddVocabEntries), ctx, storyID, vocabEntryIDs)
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, arg1 *story.Story) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, arg1)
}

// Get mocks base method.
func (m *MockRepository) Get(ctx context.Context, userID, id uuid.UUID) (*story.Story, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, userID, id)
	ret0, _ := ret[0].(*story.Story)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRepositoryMockRecorder) Get(ctx, userID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRepository)(nil).Get), ctx, userID, id)
}

// List mocks base method.
func (m *MockRepository) List(ctx context.Context, userID uuid.UUID, limit, offset int) ([]*story.Story, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]*story.Story)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRepositoryMockRecorder) List(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRepository)(nil).List), ctx, userID, limit, offset)
}
