// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/0x5d/shiru/internal/story (interfaces: VocabRepository)
//
// Generated by this command:
//
//	mockgen -destination mock/vocab_repository.go -package mock . VocabRepository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	story "github.com/0x5d/shiru/internal/story"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockVocabRepository is a mock of VocabRepository interface.
type MockVocabRepository struct {
	ctrl     *gomock.Controller
	recorder *MockVocabRepositoryMockRecorder
	isgomock struct{}
}

// MockVocabRepositoryMockRecorder is the mock recorder for MockVocabRepository.
type MockVocabRepositoryMockRecorder struct {
	mock *MockVocabRepository
}

// NewMockVocabRepository creates a new mock instance.
func NewMockVocabRepository(ctrl *gomock.Controller) *MockVocabRepository {
	mock := &MockVocabRepository{ctrl: ctrl}
	mock.recorder = &MockVocabRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVocabRepository) EXPECT() *MockVocabRepositoryMockRecorder {
	return m.recorder
}

// ListByTags mocks base method.
func (m *MockVocabRepository) ListByTags(ctx context.Context, userID uuid.UUID, tagNames []string, limit int) ([]story.VocabEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByTags", ctx, userID, tagNames, limit)
	ret0, _ := ret[0].([]story.VocabEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByTags indicates an expected call of ListByTags.
func (mr *MockVocabRepositoryMockRecorder) ListByTags(ctx, userID, tagNames, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByTags", reflect.TypeOf((*MockVocabRepository)(nil).ListByTags), ctx, userID, tagNames, limit)
}
