// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/0x5d/shiru/internal/elasticsearch (interfaces: Client)
//
// Generated by this command:
//
//	mockgen -destination mock/client.go -package mock . Client
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	elasticsearch "github.com/0x5d/shiru/internal/elasticsearch"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// EnsureIndex mocks base method.
func (m *MockClient) EnsureIndex(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureIndex", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureIndex indicates an expected call of EnsureIndex.
func (mr *MockClientMockRecorder) EnsureIndex(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureIndex", reflect.TypeOf((*MockClient)(nil).EnsureIndex), ctx)
}

// IndexStory mocks base method.
func (m *MockClient) IndexStory(ctx context.Context, doc elasticsearch.StoryDocument) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IndexStory", ctx, doc)
	ret0, _ := ret[0].(error)
	return ret0
}

// IndexStory indicates an expected call of IndexStory.
func (mr *MockClientMockRecorder) IndexStory(ctx, doc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IndexStory", reflect.TypeOf((*MockClient)(nil).IndexStory), ctx, doc)
}

// SearchStories mocks base method.
func (m *MockClient) SearchStories(ctx context.Context, userID, query string, limit, offset int) ([]elasticsearch.SearchResult, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchStories", ctx, userID, query, limit, offset)
	ret0, _ := ret[0].([]elasticsearch.SearchResult)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SearchStories indicates an expected call of SearchStories.
func (mr *MockClientMockRecorder) SearchStories(ctx, userID, query, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchStories", reflect.TypeOf((*MockClient)(nil).SearchStories), ctx, userID, query, limit, offset)
}

// Tokenize mocks base method.
func (m *MockClient) Tokenize(ctx context.Context, text string) ([]elasticsearch.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tokenize", ctx, text)
	ret0, _ := ret[0].([]elasticsearch.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Tokenize indicates an expected call of Tokenize.
func (mr *MockClientMockRecorder) Tokenize(ctx, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tokenize", reflect.TypeOf((*MockClient)(nil).Tokenize), ctx, text)
}
