// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/0x5d/shiru/internal/wanikani (interfaces: Client)
//
// Generated by this command:
//
//	mockgen -destination mock/client.go -package mock . Client
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	wanikani "github.com/0x5d/shiru/internal/wanikani"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// FetchVocabulary mocks base method.
func (m *MockClient) FetchVocabulary(ctx context.Context, apiKey string, updatedAfter *time.Time) ([]wanikani.VocabItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchVocabulary", ctx, apiKey, updatedAfter)
	ret0, _ := ret[0].([]wanikani.VocabItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchVocabulary indicates an expected call of FetchVocabulary.
func (mr *MockClientMockRecorder) FetchVocabulary(ctx, apiKey, updatedAfter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchVocabulary", reflect.TypeOf((*MockClient)(nil).FetchVocabulary), ctx, apiKey, updatedAfter)
}
