// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/0x5d/shiru/internal/anthropic (interfaces: Client)
//
// Generated by this command:
//
//	mockgen -destination mock/client.go -package mock . Client
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	anthropic "github.com/0x5d/shiru/internal/anthropic"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// GenerateStory mocks base method.
func (m *MockClient) GenerateStory(ctx context.Context, params anthropic.StoryParams) (*anthropic.StoryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateStory", ctx, params)
	ret0, _ := ret[0].(*anthropic.StoryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateStory indicates an expected call of GenerateStory.
func (mr *MockClientMockRecorder) GenerateStory(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateStory", reflect.TypeOf((*MockClient)(nil).GenerateStory), ctx, params)
}

// GenerateTags mocks base method.
func (m *MockClient) GenerateTags(ctx context.Context, surface string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateTags", ctx, surface)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateTags indicates an expected call of GenerateTags.
func (mr *MockClientMockRecorder) GenerateTags(ctx, surface any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateTags", reflect.TypeOf((*MockClient)(nil).GenerateTags), ctx, surface)
}

// GenerateTagsBatch mocks base method.
func (m *MockClient) GenerateTagsBatch(ctx context.Context, surfaces []string) (map[string][]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateTagsBatch", ctx, surfaces)
	ret0, _ := ret[0].(map[string][]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateTagsBatch indicates an expected call of GenerateTagsBatch.
func (mr *MockClientMockRecorder) GenerateTagsBatch(ctx, surfaces any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateTagsBatch", reflect.TypeOf((*MockClient)(nil).GenerateTagsBatch), ctx, surfaces)
}

// GenerateTopics mocks base method.
func (m *MockClient) GenerateTopics(ctx context.Context, tags []string, jlptLevel string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateTopics", ctx, tags, jlptLevel)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateTopics indicates an expected call of GenerateTopics.
func (mr *MockClientMockRecorder) GenerateTopics(ctx, tags, jlptLevel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateTopics", reflect.TypeOf((*MockClient)(nil).GenerateTopics), ctx, tags, jlptLevel)
}

// RankTags mocks base method.
func (m *MockClient) RankTags(ctx context.Context, topic string, tags []string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RankTags", ctx, topic, tags)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RankTags indicates an expected call of RankTags.
func (mr *MockClientMockRecorder) RankTags(ctx, topic, tags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RankTags", reflect.TypeOf((*MockClient)(nil).RankTags), ctx, topic, tags)
}
