// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/0x5d/shiru/internal/elevenlabs (interfaces: Client)
//
// Generated by this command:
//
//	mockgen -destination mock/client.go -package mock . Client
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// GenerateSpeech mocks base method.
func (m *MockClient) GenerateSpeech(ctx context.Context, voiceID, text string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateSpeech", ctx, voiceID, text)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateSpeech indicates an expected call of GenerateSpeech.
func (mr *MockClientMockRecorder) GenerateSpeech(ctx, voiceID, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateSpeech", reflect.TypeOf((*MockClient)(nil).GenerateSpeech), ctx, voiceID, text)
}
