// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/0x5d/shiru/internal/audio (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination mock/repository.go -package mock . Repository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	audio "github.com/0x5d/shiru/internal/audio"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, arg1 *audio.StoryAudio) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, arg1)
}

// GetByStoryID mocks base method.
func (m *MockRepository) GetByStoryID(ctx context.Context, storyID uuid.UUID) (*audio.StoryAudio, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByStoryID", ctx, storyID)
	ret0, _ := ret[0].(*audio.StoryAudio)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByStoryID indicates an expected call of GetByStoryID.
func (mr *MockRepositoryMockRecorder) GetByStoryID(ctx, storyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByStoryID", reflect.TypeOf((*MockRepository)(nil).GetByStoryID), ctx, storyID)
}
